apiVersion: apps/v1
kind: Deployment
metadata:
  name: langchain-server
  labels:
    app: langchain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: langchain
  template:
    metadata:
      labels:
        app: langchain
    spec:
      containers:
        - name: langchain-container
          image: tig0826/dqx-deepseek:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "6Gi"
              cpu: "2"
            limits:
              memory: "8Gi"
              cpu: "4"
          env:
            - name: TRINO_HOST
              value: "trino.mynet"
            - name: TRINO_PORT
              value: "80"
            - name: TRINO_USER
              value: "tig"
            - name: TRINO_CATALOG
              value: "iceberg"
            - name: TRINO_SCHEMA
              value: "dqx"
---
apiVersion: v1
kind: Service
metadata:
  name: langchain-service
spec:
  selector:
    app: langchain
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP

